number1 = input("Number: ")
adjective1 = input("Adjective: ")
place1 = input("A place: ")
adjective2 = input("Adjective: ")
animal1 = input("Animal (Plural): ")
adjective3 = input("Adjective: ")
noun1 = input("Plural Noun: ")
verb1 = input("Verb: ")
noun2 = input("Noun: ")
place2 = input("A place: ")
person1 = input("Person in room: ")
food1 = input("Type of food: ")
noun3 = input("Plural Noun: ")
place3 = input("A place: ")
animal2 = input("Animal: ")
verb2 = input("Verb: ")
noun4 = input("Plural Noun: ")

print ("Welcome To The Future")
print ()
print (f"It's the year {number1} and life is hard. A group of {adjective1} robots have taken control of (the) {place1}.")
print (f"They're using their magic weapons to turn {adjective2} human beings into {animal1}. Things are bad.")
print (f"There are {adjective3} {noun1} oozing out of the streets. It isn't safe anymore. You used to be able to {verb1}, but not anymore.")
print (f" A/An {noun2} could see you and throw you in the {place2} jail. I spoke to {person1} about getting more {food1}. The stash that we")
print (f" have tastes like rotten {noun3}. We're hiding out in (the) {place3} now, but who knows what will happen next? A group of angry")
print (f"{animal2}-Men could strike at any time. Maybe we should {verb2} once and for all. Maybe it's time to raise our {noun4} in the air")
print (f" and fight for what's right. That's what heroes would do.")