#This is Amanda's computerized MadLibs created January 29th,2026

#added January 29th,2026
def Welcome_To_The_Future():
    number1 = input("Number: ")
    adjective1 = input("Adjective: ")
    place1 = input("A place: ")
    adjective2 = input("Adjective: ")
    animal1 = input("Animal (Plural): ")
    adjective3 = input("Adjective: ")
    noun1 = input("Plural Noun: ")
    verb1 = input("Verb: ")
    noun2 = input("Noun: ")
    place2 = input("A place: ")
    person1 = input("Person in room: ")
    food1 = input("Type of food: ")
    noun3 = input("Plural Noun: ")
    place3 = input("A place: ")
    animal2 = input("Animal: ")
    verb2 = input("Verb: ")
    noun4 = input("Plural Noun: ")

    print ("Welcome To The Future")
    print ()
    print (f"It's the year {number1} and life is hard. A group of {adjective1} robots have taken control of (the) {place1}.")
    print (f"They're using their magic weapons to turn {adjective2} human beings into {animal1}. Things are bad.")
    print (f"There are {adjective3} {noun1} oozing out of the streets. It isn't safe anymore. You used to be able to {verb1}, but not anymore.")
    print (f" A/An {noun2} could see you and throw you in the {place2} jail. I spoke to {person1} about getting more {food1}. The stash that we")
    print (f" have tastes like rotten {noun3}. We're hiding out in (the) {place3} now, but who knows what will happen next? A group of angry")
    print (f"{animal2}-Men could strike at any time. Maybe we should {verb2} once and for all. Maybe it's time to raise our {noun4} in the air")
    print (f" and fight for what's right. That's what heroes would do.")

#added January 30th, 2026
def Deepest_Apologies():
    name1 = input("Last Name: ")
    adjective1 = input("Adjective: ")
    noun1 = input("Noun: ")
    place1 = input("A place: ")
    verb1 = input("Verb ending in 'ing': ")
    color1 = input("Color: ")
    noun2 = input("Noun: ")
    body1 = input("Part of the body: ")
    verb2 = input("Verb: ")
    body2 = input("Part of the body (plural): ")
    silly1 = input("Silly word: ")
    adjective2 = input("Adjective: ")
    noun3 = input("Noun: ")
    verb3 = input("Verb: ")
    noun4 = input("Plural Noun: ")
    noun5 = input("Noun: ")
    adjective3 = input("Adjective: ")
    person1 = input("Person in room (Male): ")

    print("Deepest Apologies")
    print()
    print(f"Dear Mrs. {name1},")
    print(f"I am truly {adjective1} for disrupting yesterday's class on the native customs of the {noun1} tribes of (the) {place1}.")
    print(f"It was rude of me to burst out {verb1} when you explained that the tribal cheif wore a/an {color1}-feathered headpiece in the")
    print(f"shape of a winged {noun2} on his {body1}. And my decision to {verb2} in a circle with my {body2} outstretched while chanting")
    print(f"'{silly1}! {silly1}!' was inappropriate - even though I was only trying to mimic the {adjective2} native dance. I understand")
    print(f"there's a time and place for that kind of {noun3} - and your class was not it. I know that you {verb3} very hard as a teacher")
    print(f"and deserve respect for teaching me and my fellow {noun4} every day. I hope you accept my sincere {noun5} and believe")
    print(f"I will never exercise such {adjective3} judgement again")
    print(f"Sincerly,")
    print(f"{person1}")

#added January 30th, 2026
def Little_League_Baseball():
    noun1 = input("Plural Noun: ")
    noun2 = input("Plural Noun: ")
    number1 = input("Number: ")
    number2 = input("Number: ")
    noun3 = input("Noun: ")
    adjective1 = input("Adjective: ")
    noun4 = input("Plural Noun: ")
    adjective2 = input("Adjective: ")
    adjective3 = input("Adjective: ")
    body1 = input("Part of the body: ")
    noun5 = input("Noun: ")
    job1 = input("Occupation (Plural): ")
    person1 = input("Person in room: ")
    
    print("Little League Baseball")
    print()
    print(f"Many future Big League baseball {noun1} are being trained in Little League today. The Little Leagues are just like")
    print(f"the Big League {noun2}, except that the players are all between {number1} and {number2} years old.")
    print(f"When a/an {noun3} goes out for a Little League team, he is given {adjective1} tests in fielding fast")
    print(f"{noun4} and in hitting. He can either play in the {adjective2} field or in the {adjective3} field.")
    print(f"Or if he has a good throwing {body1}, he can be a pitcher or catcher. If he can't do anything, he can sit on the")
    print(f"{noun5}. But no matter what position he plays, a Little Leaguer learns to work with his fellow {job1}. If you")
    print(f"play with a Little League team, who knows, you may become a famous Big League baseball player like {person1}")
    
#Added February 1st, 2026
def Vacations():
    adjective1 = input("Adjective: ")
    adjective2 = input("Adjective: ")
    noun1 = input("Noun: ")
    noun2 = input("Noun: ")
    noun3 = input("Plural Noun: ")
    game1 = input("Game: ")
    noun4 = input("Plural Noun: ")
    verb1 = input("Verb ending in 'ing': ")
    verb2 = input("Verb ending in 'ing': ")
    noun5 = input("Plural Noun: ")
    verb3 = input("Verb ending in 'ing': ")
    noun6 = input("Noun: ")
    plant1 = input("Plant: ")
    body1 = input("Part of the body: ")
    place1 = input("A place: ")
    verb4 = input("Verb ending in 'ing': ")
    adjective3 = input("Adjective: ")
    number1 = input("Number: ")
    noun7 = input("Plural Noun: ")
    
    print("Vacations")
    print()
    print(f"A vacation is when you take a trip to some {adjective1} place with your {adjective2} family. Usually you go to some place that is near a/an {noun1} or up on a/an {noun2}.")
    print(f"A good vacation place is one where you can ride {noun3} or play {game1} or go hunting for {noun4}. I like to spend my time {verb1} or {verb2}.")
    print(f"When parents go on a vacation, they spend their time eating three {noun5} a day, and fathers play golf, and mothers sit around {verb3}. Last summer, my little brother")
    print(f"fell in a/an {noun6} and got poison {plant1} all over his {body1}. My family is going to (the) {place1}, and I will practice {verb4}. Parents need vacations more than kids")
    print(f"because parents are always very {adjective3} and because they have to work {number1} hours every day all year making enough {noun7} to pay for the vacation")
    

#Added February 10th, 2026
def A_Peanut_and_His_Pooch():
     animal1 = input("Animal: ")
     adjective1 = input("Adjective: ")
     adjective2 = input("Adjective: ")
     adjective3 = input("Adjective: ")
     noun1 = input("Noun: ")
     noun2 = input("Noun: ")
     adjective4 = input("Adjective: ")
     food1 = input("Type of food: ")
     place1 = input("A place: ")
     adjective5 = input("Adjective: ")
     place2 = input("A place: ")
     noun3 = input("Noun: ")
     noun4 = input("Noun: ")
     noun5 = input("Noun: ")
     
     print("A Peanut and His Pooch")
     print()
     print(f"If you've ever met my {animal1}, Snoopy, then you know he's not your average canine companion. Some kids might find it {adjective1} that their beagle")
     print(f"has such a/an {adjective2} imagination, but not me! All I've ever wanted was a normal, {adjective3} dog. Why can't I have a/an {noun1} just like everyone")
     print(f"else? Instead, I've got a part-time pet, part-time World War I pilot, part-time {noun2}, and a full-time pain! {adjective4} grief! Sometimes he looks")
     print(f"at me like I'm chopped {food1}-good for nothing except bringing his dinner out to (the) {place1}. Still, it sure is nice to have someone with really {adjective5}")
     print(f"ears around. And after a long day at (the) {place2}, there's nothing better than coming home to a wet {noun3} on the cheek. Aw, who am I kidding?")
     print(f"I'm really lucky to have a/an {noun4} like Snoopy. They don't call dogs man's best {noun5} for nothing!")

print("1. Welcome To The Future")
print("2. Deepest Apologies")
print("3. Little League Baseball")
print("4. Vacations")
print("5. A Peanut and His Pooch")
story = input("Enter the number of the Mad Lib you'd like to do: ")
if story == "1":
    Welcome_To_The_Future()
if story == "2":
    Deepest_Apologies()
if story == "3":
    Little_League_Baseball()
if story == "4":
    Vacations()
if story == "5":
    A_Peanut_and_His_Pooch()
